### ISSUE TITLE
Pulling singularity images vs. docker images

### ISSUE THREAD

**Issue by civier** [NeuroDesk/caid#22]
Is it really faster for international users to pull docker images over singularity images?
If there was a singularity hub comparable to docker hub (I don't really know the current state of things), wouldn't it be faster to pull singularity images diretly?

On one hand, the singularity images are usually smaller than the docker images + we save the time required to unpack and convert to sif (which is quite long, unfortunately).
On the other hand, docker images that share layers will obviously be downloaded faster.

@stebo85 @aswinnarayanan  Do you know if the packages share a lot of stuff between them? how big are the base layers they share?

**Comment by stebo85** [comment]
Singularity containers are now implemented :)
