### ISSUE TITLE
Deploy singularity images to singularity hub

### ISSUE THREAD

**Issue by aswinnarayanan** [NeuroDesk/caid#5]

**Comment by stebo85** [comment]
problem: the free version only gives us 10gb of storage - or did I do something wrong? Should we setup an Australian Registry with  ARDC?

**Comment by aswinnarayanan** [comment]
@stebo85, with singularity pull from dockerhub also resolving any singularity version issues, should we close this? That seems like the most reliable method for now

**Comment by stebo85** [comment]
yes, I agree. Let's have someone else push the australian singularity hub - I think we can totally live with what we are doing now and can focus on more features :)
